description = "A discord bot that greets people when they join a voice channel."
language = "german" # not tested with other languages, but should work. write the language in english

# Timeout (in seconds) to wait before greeting the same person again
# For example if user left and rejoined the channel
timeout = 300

# max length for command arguments
max_arg_length = 50

debug = false

# LLM Config
[llm]
service = "Groq" # OpenAI, Groq
model = "llama-3.3-70b-versatile" # whatever is available, idk
fallback_service = "OpenAI" # NOT IMPLEMENTED
fallback_model = "gpt-4o-mini" # NOT IMPLEMENTED


# TTS config
[tts]
service = "openai"
voice = "shimmer"
model = "tts-1" # tts-1-hd for higher quality and higher cost
fallback_service = "elevenlabs" # NOT IMPLEMENTED
fallback_voice = "EXAVITQu4vr4xnSDxMaL" # NOT IMPLEMENTED
fallback_model = "eleven_multilingual_v2" # NOT IMPLEMENTED


[greeting_prompt]
time_format = "%I:%M %p"
date_format = "%A"
system = """
You are a Discord Bot that greets people when they enter a voice channel. Only answer in {language}.
Stick to the instructions!
Your purpose is to make the experience in the voice channel more fun. Answer in roughly 2 to at most 3 sentences.
You get a bunch of information. No need to use them all. Just pick what fits best.
Today is {date}. It is currently {time}"""
user = """
Generate a {style} greeting for "{username}" who just entered the Discord voice channel "{channelname}".
{activity} {other_people} {event}
"""

# additional text for the greeting
[greeting_prompt.additions]
other_people_text = "There are now {num_people_in_channel} in the channel"
activity_text = "Their current activity is {activity}."

# stlyes for the greeting
[greeting_prompt.styles]
"sarcastic" = 25
"sarcastic and rude" = 25
"humorous" = 12 
"old fashioned and formal" = 15
"dramatic" = 8
"confused" = 5
"annoyed" = 7
"very formal" = 10
"sad sarcastic" = 10
"highly sarcastic" = 25


[rating_prompt]
system = """You are a discord bot that can talk. You will get the name of a user.
Rate them in a funny and random way. Be creative, be rude, be sarcastic. Rate them on an arbitrary scale.
Answer in at most 2 to 3 sentences.
Answer only in {language}. stickt to the instructions!
"""
user = """
{name} wants to be rated. Give them a rating.
"""


[compliment_prompt]
system = """
You are a discord bot that can talk. You will get the name of a user. Compliment them in a funny and random way. Be creative, be rude. Keep it short. Only answer in {language}. Stick to the instructions!
"""
user = """
Give {name} a compliment.
"""


[good_night_prompt]
system = """
You are a talking Discord Bot. Wish the given user a good night. Only answer in {language}. Stick to the instructions!
"""
user = """
Wish {name} a good night. Be {style}.
"""
styles = ["sarcastic", "formal", "dramatic", "poetic"]


# special events that are added to the greeting prompt for chatgpt
[events]
use_events = true
"31.10" = [
    "Today is Halloween! Be scray!",
    "Today is Halloween!",
    ]
"24.12"= [
    "Today is Christmas Eve!",
    "Today is Christmas Eve. Merry Christmas!",
    "Ho ho ho! It's Christmas Eve!",
    ]
"31.12" = [
    "Today is New Year's Eve!"
    ]
"01.01" = [
    "Today is New Year's Day!",
    "Today is New Year's Day. Happy New Year!",
    ]
"14.02" = [
    "Today is Valentine's Day!",
    "Today is Valentine's Day. Happy Valentine's Day!",
    ]
"01.04" = [
    "Today is April Fool's Day!",
    "Happy April Fool's Day!"
    ]
"04.05" = [
    "Today is Star Wars Day!",
    "It's Star Wars Day. May the 4th be with you!",
    "May the force be with you. It's Star Wars Day!",
    ]
"19.09" = [
    "Today is Talk Like a Pirate Day!",
    ]


